name: Supabase DB

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 2.89.0

      - name: Start local Supabase stack
        run: supabase start

      - name: Lint database schema
        run: supabase db lint --local --schema public --fail-on error
